blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/papyrxis/https://github.com/papyrxis/workspace/discussions
    about: Ask questions and discuss ideas
